name: main
on:
  workflow_dispatch:
  push:
    branches:
      - "**"


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0

  small-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install jobsim
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: run small-tests
        run: poetry run python -m pytest -v --junitxml=small_tests_results.xml tests/small

      - uses: actions/upload-artifact@v3
        with:
          name: small_tests_results
          path: small_tests_results.xml
        if: always()
          
  large-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install jobsim
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: run large-tests
        run: poetry run python -m pytest -v --junitxml=large_tests_results.xml tests/large

      - uses: actions/upload-artifact@v3
        with:
          name: large_tests_results
          path: large_tests_results.xml
        if: always()

  report_workflow:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - small-tests
      - large-tests
    steps:
      - uses: uoboda-splunk/workflow-info-splunk-upload-action@v1
        with:
          splunk_host: ${{ secrets.SPLUNK_HOST }}
          splunk_token: ${{ secrets.SPLUNK_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
